---
- name: Check arguments
  assert:
    that:
      - tomcat.service is defined
      - tomcat.user is defined
      - tomcat.group is defined
      - tomcat.service.conf is defined
      - tomcat.service.script is defined

- name: "Ensure requirements for systemd"
  include_tasks: ../fastpackage.yml
  vars:
    package_name: "{{ item }}"
  loop:
    - systemd
    - procps-ng

- name: "Ensure service script is deployed"
  template:
    src: templates/systemd/service.sh.j2
    dest: "{{ tomcat.service.script }}"
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
    mode: 0755

- name: "Ensure service configurations files is deployed: {{ tomcat.service.conf }}"
  template:
    src: templates/systemd/tomcat.conf.j2
    dest: "{{ tomcat.service.conf }}"
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
    mode: 0644
  vars:
    tomcat_rpm_java_home: "{{ rpm_java_home.stdout if rpm_java_home is defined else '/usr/lib/jvm/java' }}"
  notify:
    - Systemd reload
    - Ensure Tomcat runs under systemd

- name: "Ensure systemd service is configured"
  template:
    src: templates/systemd/tomcat.service.j2
    dest: "{{ tomcat.service.systemd }}"
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
    mode: 0644
  notify:
    - Systemd reload
    - Ensure Tomcat runs under systemd
